### ISSUE TITLE
Unable to parse xml with multiline comment

### ISSUE THREAD

**Issue by Ajay-MS** [node-xmpp/ltx#100]
Hello Team, 

While trying to parse an xml document with multi-line comment , getting error Incomplete document.

**Comment by Ajay-MS** [comment]
Issue was not with multi-line comments. Its when if a comment contains some other tag.  I have create PR corresponding to issue. Please take a look and fix mentioned issue. Thanks in advance.

[PR - tags in comment fix](https://github.com/node-xmpp/ltx/pull/101/files)

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/ltx/pull/102

**Comment by sonnyp** [comment]
fixed and publish in ltx 2.5.1

**Comment by sonnyp** [comment]
@Ajay-MS thanks
