### ISSUE TITLE
toString() function encodes XML escape characters by default

### ISSUE THREAD

**Issue by vincentdass** [node-xmpp/ltx#115]
LTx parser writes the DOM with HTML encoding by default.

`<tag name="NodeName" websiteName="ValueOfWebsiteName" connectionStrinng="{name: 'myconnection'}" />`
gets replaced to 
` <tag name="NodeName" websiteName="ValueOfWebsiteName" connectionStrinng="{name: &apos;myconnection&apos;}"/>`

When looking at the code,it is found that  encoding is made by [default](https://github.com/node-xmpp/ltx/blob/master/lib/Element.js#L363). Should it be made optional ?

My XML file has other tags with HTML encoded strings. So, I am unable to use unescapeXML function while converting to string.
 
`<compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />`

**Comment by sonnyp** [comment]
@vincentdass `'` is not allow in XML attribute values so I'm not sure what you expect.

**Comment by vincentdass** [comment]
@sonnyp , thanks for the quick response.
Referring to this [stackoverflow](http://stackoverflow.com/a/1091953) post, it is found that ' (single quotes) are valid in XML attributes, when they are enclosed by double quotes.
I tried parsing and substitution with [xmldom](https://www.npmjs.com/package/xmldom) and it worked fine. There was no XML special characters encoding by default in the above package. 

My expectation is XML special characters should not be encoded by default, it is purely users' choice.

**Comment by sonnyp** [comment]
Okay my bad. I wouldn't make anything optional though, just encode what needs to be however encoding only what needs to be does require some work, the current behaviour is functional and safe so it's definitely low priority for me but if anyone is willing to work on this; please do so.

**Comment by sonnyp** [comment]
Okay my bad. I wouldn't make anything optional though, just encode what needs to be however encoding only what needs to be does require some work, the current behaviour is functional and safe so it's definitely low priority for me but if anyone is willing to work on this; please do so.

**Comment by vincentdass** [comment]
@sonnyp , Can you please add me to this repo ?
I would like to contribute here.

**Comment by astro** [comment]
> `<tag name="NodeName" websiteName="ValueOfWebsiteName" connectionStrinng="{name: 'myconnection'}" />`
gets replaced to 
` <tag name="NodeName" websiteName="ValueOfWebsiteName" connectionStrinng="{name: &apos;myconnection&apos;}"/>`

They're equivalent so there isn't much point to this?

> Can you please add me to this repo ?

Could you please work with Pull Requests so that your contributions can be reviewed?
