### ISSUE TITLE
How to send HTML formatted message?

### ISSUE THREAD

**Issue by saurabhm27** [node-xmpp/ltx#116]
Hi 

I am using node-xmpp-client module and want to send HTML messages to client.
Below is my code snippet which doesn't work due to obvious reasons.

Can you suggest how to send HTML messages?

Thanks
Saurabh

-----------------------------------------------------------------------------------------
if (stanza.is('message') && stanza.attrs.type === 'chat'  ) {
        
      
       
        var reply = new xmpp.Client.Stanza('message', {
            to: stanza.attrs.from,
            from: stanza.attrs.to,
            type: 'chat'
        })
       
        
        reply.c('body').t("<a href='http://www.google.com'>Google</a>);
         console.log(firstMessage)
    
        if (firstMessage)
            {
            firstMessage = false
            }
        else{
            firstMessage = true;
            client.send(reply);
            
        }
    }    
------------------------------------------------------------------------

**Comment by sonnyp** [comment]
https://xmpp.org/rfcs/rfc6121.html#message-syntax-extended

**Comment by sonnyp** [comment]
so something like

```
reply.c('html', {xmlns: 'http://jabber.org/protocol/xhtml-im'}).c('body', {xmlns: 'http://www.w3.org/1999/xhtml'}).c('a', {href: 'http://www.google.com'}).t('Google')
```

**Comment by sonnyp** [comment]
Maybe we should have something like `innerHTML` in ltx, what do you think?

**Comment by saurabhm27** [comment]
Thanks for your quick response.

After using your suggestion "reply.c('html', {xmlns: 'http://jabber.org/protocol/xhtml-im'}).c('body', {xmlns: 'http://www.w3.org/1999/xhtml'}).c('a', {href: 'http://www.google.com'}).t('Google')"

I received http://www.google.com on the client

**Comment by saurabhm27** [comment]
update:

HTML tags in general are working... e.g.
reply.c('html', {xmlns: 'http://jabber.org/protocol/xhtml-im'}).c('body', {xmlns: 'http://www.w3.org/1999/xhtml'}).c('font', {color: 'red'}).t('Google!!!')

However, hyperlink is not. when using anchor element the url gets displayed.

**Comment by sonnyp** [comment]
@saurabhm27 can you provide an example?

**Comment by saurabhm27** [comment]
if (stanza.is('message') && stanza.attrs.type === 'chat'  ) {
        
      
       
        var reply = new xmpp.Client.Stanza('message', {
            to: stanza.attrs.from,
            from: stanza.attrs.to,
            type: 'chat'
        })
       
        
     
        
        
       // reply.c('html', {xmlns: 'http://jabber.org/protocol/xhtml-im'}).c('body', {xmlns: 'http://www.w3.org/1999/xhtml'}).c('a', {href: 'http://www.google.com'}).t('Google') // the jabber client receives http://www.google.com. The word Google is omitted.
        
        
        reply.c('html', {xmlns: 'http://jabber.org/protocol/xhtml-im'}).c('body', {xmlns: 'http://www.w3.org/1999/xhtml'}).c('font', {color: 'red'}).t('Google!!!')  // the jabber client receives Google!!! in red color.
        
    console.log('Serialized document:', reply.root().toString());
         
        if (firstMessage)
            {
            firstMessage = false
            }
        else{
            firstMessage = true;
            client.send(reply);
            
        }
    }

**Comment by sonnyp** [comment]
Looks like an issue with your client, not with ltx.

**Comment by saurabhm27** [comment]
Thanks for your time.. Yes, I found out that XMPP has a security feature where it displays the value of the XHTML ’href’ attribute instead of the XML character data of the <a/> element.


________________________________
