### ISSUE TITLE
Element.write might break unicode

### ISSUE THREAD

**Issue by dodo** [node-xmpp/ltx#29]
look like [Element.write](https://github.com/node-xmpp/ltx/blob/master/lib/element.js#L252) breaks unicode symbols when sending them chunked over a socket.

problem spotted over at node-xmpp/node-xmpp#198

**Comment by sonnyp** [comment]
is this still an issue? looks pretty bad

**Comment by sonnyp** [comment]
cannot reproduce, might have something to do with node version
