### ISSUE TITLE
Dynamic requires break in webpack.

### ISSUE THREAD

**Issue by latentflip** [node-xmpp/ltx#55]
So webpack treats dynamic requires differently to browserify, which means by default ltx fails when building under webpack.

Given that https://github.com/node-xmpp/ltx/blob/master/lib/parse.js#L11-L33 are always going to be an exception in browserify, and reason not to pull them out and only run this code in node?

I can submit a PR, just wanna check there's no good reason for it being this way?

**Comment by lloydwatkin** [comment]
There's no good reason for it being this way as far as I know. PR to your heart's content :)

**Comment by sonnyp** [comment]
See https://github.com/node-xmpp/ltx/pull/65
