### ISSUE TITLE
ltx.Parser doesn't emit startElement

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/ltx#57]
ltx.Parser abstraction over the different ltx 'backends' doesn't emit ```startElement```, ```endElement```, ... events

**Comment by astro** [comment]
As a "DOM parser" it emits only `tree` when parsing is done.

However you can attach events on `parser.parser`. Nice enough API?

**Comment by sonnyp** [comment]
@astro yes I'm already using ```parser.parser``` but shouldn't ```ltx.Parser``` emit those as well?

**Comment by astro** [comment]
It's a DOM parser. I fear that proxying these events when no one is using them hurts performance needlessly.

**Comment by sonnyp** [comment]
right :+1:
