### ISSUE TITLE
IE8 could not run Object.defineProperty function

### ISSUE THREAD

**Issue by EricTiger1986** [node-xmpp/ltx#92]
Currently, I am working on an XMPP project. This project should be supported in IE8. But I found IE8 could not support Object.defineProperty. So some codes in DOMElement.js will break the project.
I have tried to use es5-sham.js and es5-shim.js to solve this question, but I found Object.defineProperty implemented in es5-sham.js was via **defineGetter** and **defineSetter**. These two functions are still not implemented in IE8. Who could help me? Thank you in advance.

**Comment by sonnyp** [comment]
Hello,

We don't support IE8 at the moment. What do you need DOMElement.js for?

**Comment by EricTiger1986** [comment]
Another module JXT needs.

**Comment by sonnyp** [comment]
It's not impossible to get IE8 support in DOMElement.js but I'd say it's useless because stanza.io doesn't support IE8 anyway.

If you need IE8 you might wanna to look at [Strophe.js](http://strophe.im/strophejs/)

**Comment by sonnyp** [comment]
cc @legastero
