### ISSUE TITLE
Removal of toJSON should be a major version upgrade?

### ISSUE THREAD

**Issue by hyperlink** [node-xmpp/ltx#95]
I did a new install of our project this morning and discovered our test failing at `toJSON`.

Looks like this was caused by changes in PR #91 to remove the `toJSON` method. Shouldn't any removals should made in an backwards incompatible manner be a bump in [major version](http://semver.org/#spec-item-8)?

@sonnyp if you want I can create a PR to put this back. Thanks!

**Comment by sonnyp** [comment]
Sorry for the inconvenience.

`toJSON` was an undocumented feature but I shouldn't have assumed it wasn't being used.

It would be very helpful if you could make the PR and I'll realase as a minor version.

**Comment by hyperlink** [comment]
PR #97

**Comment by sonnyp** [comment]
published as `2.4.1`
